server:
  port: ${AUTH_SERVICE_PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

host:
  client: ${CLIENT_SERVICE_HOST}
  worker: ${WORKER_SERVICE_HOST}

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${AUTH_DB_HOST}:5432/auth-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 804317373743-ct8qt00tjb7s1ooh6e1ng3ejred9pd27.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
