server:
  port: 8089

spring:
  application:
    name: leasing

  datasource:
    url: jdbc:postgresql://${LEASING_DB_HOST}:5438/leasing-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.greenflow: debug
