version: "3.9"

services:
  auth-db:
    image: bitnami/postgresql:16.1.0-debian-11-r25
    container_name: auth-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-db
    ports:
        - "5432:5432"

  worker-db:
    image: bitnami/postgresql:16.1.0-debian-11-r25
    container_name: worker-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: worker-db
    ports:
      - "5433:5432"

  client-db:
    image: bitnami/postgresql:16.1.0-debian-11-r25
    container_name: client-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: client-db
    ports:
      - "5434:5432"


volumes:
  pg_data:
    driver: local