version: "3.9"

services:
  auth-db:
    image: bitnami/postgresql:16.1.0-debian-11-r25
    container_name: auth-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-db
    ports:
        - "5432:5432"

  worker-db:
    image: bitnami/postgresql:16.1.0-debian-11-r25
    container_name: worker-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: worker-db
    ports:
      - "5433:5432"

  client-db:
    image: bitnami/postgresql:16.1.0-debian-11-r25
    container_name: client-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: client-db
    ports:
      - "5434:5432"

  garden-db:
    image: bitnami/postgresql:16.1.0-debian-11-r25
    container_name: garden-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garden-db
    ports:
      - "5435:5432"

  order-db:
    image: bitnami/postgresql:16.1.0-debian-11-r25
    container_name: order-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order-db
    ports:
      - "5437:5432"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - rabbitmq:/data
    networks:
      greenflow:
        aliases:
          - rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      greenflow:
        aliases:
          - redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  equipment-db:
    image: mongo:latest
    container_name: equipment-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: equipment-db
    volumes:
      - mongo:/data
    networks:
        greenflow:
            aliases:
            - equipment-db
    ports:
      - "27017:27017"

  leasing-db:
    image: bitnami/postgresql:16.1.0-debian-11-r25
    container_name: leasing-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leasing-db
    ports:
      - "5438:5432"


volumes:
  pg_data:
    driver: local
  redis:
    driver: local
  rabbitmq:
    driver: local
  mongo:
    driver: local

networks:
  greenflow:
    name: greenflow
