version: "3.9"

services:
  auth-db:
    image: bitnami/postgresql:16.1.0-debian-11-r25
    container_name: auth-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-db
    ports:
        - "5432:5432"



volumes:
  pg_data:
    driver: local