server:
  port: 8080

service:
  auth:
    host: ${AUTH_SERVICE_HOST}
  client:
    host: ${CLIENT_SERVICE_HOST}
  equipment:
    host: ${EQUIPMENT_SERVICE_HOST}
  garden:
    host: ${GARDEN_SERVICE_HOST}
  openOrder:
    host: ${OPEN_ORDER_SERVICE_HOST}
  order:
    host: ${ORDER_SERVICE_HOST}
  worker:
    host: ${WORKER_SERVICE_HOST}
  payment:
    host: ${PAYMENT_SERVICE_HOST}

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: api-gateway

logging:
  level:
    org.greenflow: DEBUG
    root: debug