server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: api-gateway

  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
        all-namespaces: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    greenflow: DEBUG