server:
  port: 8083

spring:
  application:
    name: worker

  datasource:
    url: jdbc:postgresql://${WORKER_DB_HOST}:5433/worker-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.greenflow: debug

host:
  billing: ${BILLING_SERVICE_HOST}
