server:
  port: 8087

spring:
  application:
    name: equipment

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/equipment-db
      authentication-database: admin

datasource:
  equipment:
    uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/equipment-db
    authentication-database: admin
  leasing:
    url: jdbc:postgresql://${LEASING_DB_HOST}:5438/leasing-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    ddl-auto: update


logging:
  level:
    org.greenflow: debug