server:
  port: ${EQUIPMENT_SERVICE_PORT}

spring:
  application:
    name: equipment

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/equipment
      database: equipment-db
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

logging:
  level:
    greenflow: DEBUG