server:
  port: 8087

spring:
  application:
    name: equipment

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/equipment-db
      authentication-database: admin

logging:
  level:
    org.greenflow: debug