server:
  port: 0

spring:
  application:
    name: garden

  datasource:
    url: jdbc:postgresql://${GARDEN_DB_HOST}:5435/garden-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    hostname: ${GARDEN_HOSTNAME}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    greenflow: DEBUG