server:
  port: 8084

spring:
  application:
    name: garden

  datasource:
    url: jdbc:postgresql://${GARDEN_DB_HOST}:5435/garden-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.greenflow: DEBUG

api:
  spaces:
    access-key: ${SPACES_ACCESS_KEY}
    secret-key: ${SPACES_SECRET_KEY}
    uri: ${SPACES_URI}
    region: ${SPACES_REGION}