server:
  port: ${GARDEN_SERVICE_PORT}

spring:
  application:
    name: garden

  datasource:
    url: jdbc:postgresql://${GARDEN_DB_HOST}:5435/garden-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    greenflow: DEBUG