apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garden
  template:
    metadata:
      labels:
        app: garden
    spec:
      containers:
        - name: garden
          image: kartosha/greenflow.garden:latest
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 400Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: config-map
---
apiVersion: v1
kind: Service
metadata:
  name: garden
spec:
  type: ClusterIP
  selector:
    app: garden
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084