apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-order
  template:
    metadata:
      labels:
        app: open-order
    spec:
      containers:
        - name: open-order
          image: kartosha/greenflow.open-order:latest
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 400Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: config-map
---
apiVersion: v1
kind: Service
metadata:
  name: open-order
spec:
  type: ClusterIP
  selector:
    app: open-order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086