apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: equipment-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: equipment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equipment-db
  template:
    metadata:
      labels:
        app: equipment-db
    spec:
      containers:
        - name: equipment-db
          image: mongo:latest
          env:
            - name: MONGO_INITDB_DATABASE
              value: equipment-db
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: equipment-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: equipment-db
spec:
  selector:
    app: equipment-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
