apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-db
  template:
    metadata:
      labels:
        app: worker-db
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:16.1.0-debian-11-r25
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "worker-db"
          ports:
            - containerPort: 5433
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: worker-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: worker-db
spec:
  selector:
    app: worker-db
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432