server:
  port: 8082

spring:
  application:
    name: client

  datasource:
    url: jdbc:postgresql://${CLIENT_DB_HOST}:5434/client-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.greenflow: DEBUG

host:
  billing: ${BILLING_SERVICE_HOST}