server:
  port: 0

spring:
  application:
    name: client

  datasource:
    url: jdbc:postgresql://${CLIENT_DB_HOST}:5434/client-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    greenflow: DEBUG