name: API Gateway CI/CD

on:
  push:
    paths:
      - 'api-gateway/**'
      - 'common/**'
      - '.github/workflows/api-gateway.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew in api-gateway
        run: chmod +x api-gateway/gradlew

      - name: Run tests in api-gateway
        run: cd api-gateway && ./gradlew test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Use the root of the repository to include common and api-gateway
          file: ./api-gateway/Dockerfile  # Path to the Dockerfile
          push: true
          tags: kartosha/greenflow.api-gateway