name: API Gateway CI/CD

on:
  push:
    paths:
      - 'eureka/**'
      - '.github/workflows/eureka.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew in eureka
        run: chmod +x eureka/gradlew

      - name: Run tests in eureka
        run: cd eureka && ./gradlew test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Use the root of the repository to include common and eureka
          file: ./eureka/Dockerfile  # Path to the Dockerfile
          push: true
          tags: kartosha/greenflow.eureka