name: Open Order CI/CD

on:
  push:
    paths:
      - 'open-order/**'
      - 'common/**'
      - '.github/workflows/open-order.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew in common
        run: chmod +x common/gradlew

      - name: Test and publish common to mavenLocal
        run: cd common && ./gradlew test publishToMavenLocal

      - name: Grant execute permission for gradlew in open-order
        run: chmod +x open-order/gradlew

      - name: Run tests in open-order
        run: cd open-order && ./gradlew test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Use the root of the repository to include common and open-order
          file: ./open-order/Dockerfile  # Path to the Dockerfile
          push: true
          tags: |
            kartosha/greenflow.worker:latest
            kartosha/greenflow.worker:${{ github.sha }}      

      - name: Set up Kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_DATA" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/worker worker=kartosha/greenflow.worker:${{ github.sha }}
          kubectl rollout status deployment/worker